### ISSUE TITLE
Problem Statement Draft

### ISSUE THREAD

**Issue by aschaap** [aschaap/cas741#1]
@smiths
Hello Dr. Smith,

I've committed and pushed the first draft of my problem statement. I've included the [PDF](https://github.com/aschaap/cas741/blob/master/Doc/ProblemStatement/ProblemStatement.pdf). Please let me know if anything needs to be improved.

**Comment by smiths** [comment]
Good start on  your abstract.  I made a few minor LaTeX observations and I'll pushed a new version with my comments momentarily.

I'm not quite ready to approve your problem statement.  It has an emphasis on how you are going to solve the problem, but it doesn't really say what you are doing.  Rather than emphasize the meta programming aspect, I would like you to say that your project is to create a family of ODE solvers.  I don't think you even need to restrict the scope to RKF45 at this time.  I also think you should position this work as a library, since the goal is to create something that can be used by another program.

If you have any questions, please let me know.

**Comment by aschaap** [comment]
I've committed and pushed changes that I hope address your concerns. Therefore, my question is "Is this a step in the right direction?"

Thank you.

**Comment by smiths** [comment]
Looks great.  Thank you.
