### ISSUE TITLE
The term OCaml and MetaOCaml are not defined

### ISSUE THREAD

**Issue by renjiezhang** [aschaap/cas741#29]
I am not sure what OCaml and MetaOCaml are. You need to have them in the symbol table

**Comment by renjiezhang** [comment]
@smiths

**Comment by aschaap** [comment]
They are not really symbols,  abbreviations or acronyms, so I don't think they belong there. OCaml is a programming language; MetaOCaml is an extension of OCaml that adds metaprogramming (staging, in this case) support. Nevertheless, I've tried to clarify this by mentioning the word 'code', so that one may infer that they are programming languages. I also mentioned this document follows from the SRS and linked to it.
